
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Titillium_Web } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
import { SelectedCarAmountContext } from '@/context/selectedCarAmount'
import CarAmountProvider from '@/components/CarAmountProvider'


const ubuntu = Titillium_Web({ subsets: ['latin'], weight: '700' })

export const metadata = {
  title: 'CabConnect',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  return (
    <ClerkProvider>
      <html lang="en" className='h-[100vh]'>
        <body className={`${ubuntu.className} h-full`} >
        <CarAmountProvider>
          <Navbar />
          {children}
        </CarAmountProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
