import { Titillium_Web } from 'next/font/google'

const ubuntu = Titillium_Web({ subsets: ['latin'], weight: '700' })

export const metadata = {
  title: 'CabConnect',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='h-full w-full flex justify-center items-center'>
        {children}
    </div>
  )
}